# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases
from ._compat import model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED

if TYPE_CHECKING:
    from .client import Prisma
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class PlayerActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.Player]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await Player.prisma().query_raw(
            'SELECT * FROM Player WHERE id = ?',
            1103527590,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.Player
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await Player.prisma().query_first(
            'SELECT * FROM Player WHERE name = ?',
            'dhheabfhf',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.PlayerCreateInput,
        include: Optional[types.PlayerInclude] = None
    ) -> _PrismaModelT:
        """Create a new Player record.

        Parameters
        ----------
        data
            Player record data
        include
            Specifies which relations should be loaded on the returned Player model

        Returns
        -------
        prisma.models.Player
            The created Player record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a Player record from just the required fields
        player = await Player.prisma().create(
            data={
                # data to create a Player record
                'name': 'ggciceaie',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.PlayerCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple Player records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of Player record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await Player.prisma().create_many(
            data=[
                {
                    # data to create a Player record
                    'name': 'bbehjachib',
                },
                {
                    # data to create a Player record
                    'name': 'cadfabfehe',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.PlayerWhereUniqueInput,
        include: Optional[types.PlayerInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single Player record.

        Parameters
        ----------
        where
            Player filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned Player model

        Returns
        -------
        prisma.models.Player
            The deleted Player record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        player = await Player.prisma().delete(
            where={
                'id': 368800899,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.PlayerWhereUniqueInput,
        include: Optional[types.PlayerInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique Player record.

        Parameters
        ----------
        where
            Player filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Player model

        Returns
        -------
        prisma.models.Player
            The found Player record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        player = await Player.prisma().find_unique(
            where={
                'id': 1508029952,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.PlayerWhereUniqueInput,
        include: Optional[types.PlayerInclude] = None
    ) -> _PrismaModelT:
        """Find a unique Player record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            Player filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Player model

        Returns
        -------
        prisma.models.Player
            The found Player record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        player = await Player.prisma().find_unique_or_raise(
            where={
                'id': 486256185,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PlayerWhereInput] = None,
        cursor: Optional[types.PlayerWhereUniqueInput] = None,
        include: Optional[types.PlayerInclude] = None,
        order: Optional[Union[types.PlayerOrderByInput, List[types.PlayerOrderByInput]]] = None,
        distinct: Optional[List[types.PlayerScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple Player records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of Player records returned
        skip
            Ignore the first N results
        where
            Player filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Player model
        order
            Order the returned Player records by any field
        distinct
            Filter Player records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.Player]
            The list of all Player records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 Player records
        players = await Player.prisma().find_many(take=10)

        # find the first 5 Player records ordered by the rating field
        players = await Player.prisma().find_many(
            take=5,
            order={
                'rating': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.PlayerWhereInput] = None,
        cursor: Optional[types.PlayerWhereUniqueInput] = None,
        include: Optional[types.PlayerInclude] = None,
        order: Optional[Union[types.PlayerOrderByInput, List[types.PlayerOrderByInput]]] = None,
        distinct: Optional[List[types.PlayerScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single Player record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Player filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Player model
        order
            Order the returned Player records by any field
        distinct
            Filter Player records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Player
            The first Player record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Player record ordered by the rank_id field
        player = await Player.prisma().find_first(
            skip=1,
            order={
                'rank_id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.PlayerWhereInput] = None,
        cursor: Optional[types.PlayerWhereUniqueInput] = None,
        include: Optional[types.PlayerInclude] = None,
        order: Optional[Union[types.PlayerOrderByInput, List[types.PlayerOrderByInput]]] = None,
        distinct: Optional[List[types.PlayerScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single Player record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Player filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Player model
        order
            Order the returned Player records by any field
        distinct
            Filter Player records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Player
            The first Player record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Player record ordered by the id field
        player = await Player.prisma().find_first_or_raise(
            skip=1,
            order={
                'id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.PlayerUpdateInput,
        where: types.PlayerWhereUniqueInput,
        include: Optional[types.PlayerInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single Player record.

        Parameters
        ----------
        data
            Player record data specifying what to update
        where
            Player filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned Player model

        Returns
        -------
        prisma.models.Player
            The updated Player record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        player = await Player.prisma().update(
            where={
                'id': 1062517886,
            },
            data={
                # data to update the Player record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.PlayerWhereUniqueInput,
        data: types.PlayerUpsertInput,
        include: Optional[types.PlayerInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            Player filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned Player model

        Returns
        -------
        prisma.models.Player
            The created or updated Player record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        player = await Player.prisma().upsert(
            where={
                'id': 267834847,
            },
            data={
                'create': {
                    'id': 267834847,
                    'name': 'cadfabfehe',
                },
                'update': {
                    'name': 'cadfabfehe',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.PlayerUpdateManyMutationInput,
        where: types.PlayerWhereInput,
    ) -> int:
        """Update multiple Player records

        Parameters
        ----------
        data
            Player data to update the selected Player records to
        where
            Filter to select the Player records to update

        Returns
        -------
        int
            The total number of Player records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all Player records
        total = await Player.prisma().update_many(
            data={
                'name': 'biabhbdai'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PlayerWhereInput] = None,
        cursor: Optional[types.PlayerWhereUniqueInput] = None,
    ) -> int:
        """Count the number of Player records present in the database

        Parameters
        ----------
        select
            Select the Player fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Player filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.PlayerCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Player.prisma().count()

        # results: prisma.types.PlayerCountAggregateOutput
        results = await Player.prisma().count(
            select={
                '_all': True,
                'rating': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.PlayerCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PlayerWhereInput] = None,
        cursor: Optional[types.PlayerWhereUniqueInput] = None,
    ) -> types.PlayerCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.PlayerCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PlayerWhereInput] = None,
        cursor: Optional[types.PlayerWhereUniqueInput] = None,
    ) -> Union[int, types.PlayerCountAggregateOutput]:
        """Count the number of Player records present in the database

        Parameters
        ----------
        select
            Select the Player fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Player filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.PlayerCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Player.prisma().count()

        # results: prisma.types.PlayerCountAggregateOutput
        results = await Player.prisma().count(
            select={
                '_all': True,
                'rank_id': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.PlayerCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.PlayerWhereInput] = None
    ) -> int:
        """Delete multiple Player records.

        Parameters
        ----------
        where
            Optional Player filter to find the records to be deleted

        Returns
        -------
        int
            The total number of Player records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all Player records
        total = await Player.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.PlayerScalarFieldKeys'],
        *,
        where: Optional['types.PlayerWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.PlayerAvgAggregateInput'] = None,
        sum: Optional['types.PlayerSumAggregateInput'] = None,
        min: Optional['types.PlayerMinAggregateInput'] = None,
        max: Optional['types.PlayerMaxAggregateInput'] = None,
        having: Optional['types.PlayerScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.PlayerCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.PlayerScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.PlayerScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.PlayerGroupByOutput']:
        """Group Player records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar Player fields to group records by
        where
            Player filter to select records
        take
            Limit the maximum number of Player records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.PlayerGroupByOutput]
            A list of dictionaries representing the Player record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group Player records by id values
        # and count how many records are in each group
        results = await Player.prisma().group_by(
            ['id'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]


class RankActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.Rank]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await Rank.prisma().query_raw(
            'SELECT * FROM Rank WHERE id = ?',
            836760821,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.Rank
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await Rank.prisma().query_first(
            'SELECT * FROM Rank WHERE name = ?',
            'fjfddhigg',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.RankCreateInput,
        include: Optional[types.RankInclude] = None
    ) -> _PrismaModelT:
        """Create a new Rank record.

        Parameters
        ----------
        data
            Rank record data
        include
            Specifies which relations should be loaded on the returned Rank model

        Returns
        -------
        prisma.models.Rank
            The created Rank record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a Rank record from just the required fields
        rank = await Rank.prisma().create(
            data={
                # data to create a Rank record
                'name': 'hjaecfifb',
                'min_rating': 2111915288,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.RankCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple Rank records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of Rank record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await Rank.prisma().create_many(
            data=[
                {
                    # data to create a Rank record
                    'name': 'bbejhfidcb',
                    'min_rating': 1644289366,
                },
                {
                    # data to create a Rank record
                    'name': 'bdiicjafbj',
                    'min_rating': 1647418052,
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.RankWhereUniqueInput,
        include: Optional[types.RankInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single Rank record.

        Parameters
        ----------
        where
            Rank filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned Rank model

        Returns
        -------
        prisma.models.Rank
            The deleted Rank record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        rank = await Rank.prisma().delete(
            where={
                'id': 1675546029,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.RankWhereUniqueInput,
        include: Optional[types.RankInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique Rank record.

        Parameters
        ----------
        where
            Rank filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Rank model

        Returns
        -------
        prisma.models.Rank
            The found Rank record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        rank = await Rank.prisma().find_unique(
            where={
                'id': 1767274722,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.RankWhereUniqueInput,
        include: Optional[types.RankInclude] = None
    ) -> _PrismaModelT:
        """Find a unique Rank record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            Rank filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Rank model

        Returns
        -------
        prisma.models.Rank
            The found Rank record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        rank = await Rank.prisma().find_unique_or_raise(
            where={
                'id': 326272115,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.RankWhereInput] = None,
        cursor: Optional[types.RankWhereUniqueInput] = None,
        include: Optional[types.RankInclude] = None,
        order: Optional[Union[types.RankOrderByInput, List[types.RankOrderByInput]]] = None,
        distinct: Optional[List[types.RankScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple Rank records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of Rank records returned
        skip
            Ignore the first N results
        where
            Rank filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Rank model
        order
            Order the returned Rank records by any field
        distinct
            Filter Rank records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.Rank]
            The list of all Rank records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 Rank records
        ranks = await Rank.prisma().find_many(take=10)

        # find the first 5 Rank records ordered by the min_rating field
        ranks = await Rank.prisma().find_many(
            take=5,
            order={
                'min_rating': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.RankWhereInput] = None,
        cursor: Optional[types.RankWhereUniqueInput] = None,
        include: Optional[types.RankInclude] = None,
        order: Optional[Union[types.RankOrderByInput, List[types.RankOrderByInput]]] = None,
        distinct: Optional[List[types.RankScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single Rank record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Rank filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Rank model
        order
            Order the returned Rank records by any field
        distinct
            Filter Rank records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Rank
            The first Rank record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Rank record ordered by the id field
        rank = await Rank.prisma().find_first(
            skip=1,
            order={
                'id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.RankWhereInput] = None,
        cursor: Optional[types.RankWhereUniqueInput] = None,
        include: Optional[types.RankInclude] = None,
        order: Optional[Union[types.RankOrderByInput, List[types.RankOrderByInput]]] = None,
        distinct: Optional[List[types.RankScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single Rank record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Rank filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Rank model
        order
            Order the returned Rank records by any field
        distinct
            Filter Rank records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Rank
            The first Rank record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Rank record ordered by the name field
        rank = await Rank.prisma().find_first_or_raise(
            skip=1,
            order={
                'name': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.RankUpdateInput,
        where: types.RankWhereUniqueInput,
        include: Optional[types.RankInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single Rank record.

        Parameters
        ----------
        data
            Rank record data specifying what to update
        where
            Rank filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned Rank model

        Returns
        -------
        prisma.models.Rank
            The updated Rank record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        rank = await Rank.prisma().update(
            where={
                'id': 1343201072,
            },
            data={
                # data to update the Rank record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.RankWhereUniqueInput,
        data: types.RankUpsertInput,
        include: Optional[types.RankInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            Rank filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned Rank model

        Returns
        -------
        prisma.models.Rank
            The created or updated Rank record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        rank = await Rank.prisma().upsert(
            where={
                'id': 675780521,
            },
            data={
                'create': {
                    'id': 675780521,
                    'name': 'bdiicjafbj',
                    'min_rating': 1647418052,
                },
                'update': {
                    'name': 'bdiicjafbj',
                    'min_rating': 1647418052,
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.RankUpdateManyMutationInput,
        where: types.RankWhereInput,
    ) -> int:
        """Update multiple Rank records

        Parameters
        ----------
        data
            Rank data to update the selected Rank records to
        where
            Filter to select the Rank records to update

        Returns
        -------
        int
            The total number of Rank records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all Rank records
        total = await Rank.prisma().update_many(
            data={
                'min_rating': 744964398
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.RankWhereInput] = None,
        cursor: Optional[types.RankWhereUniqueInput] = None,
    ) -> int:
        """Count the number of Rank records present in the database

        Parameters
        ----------
        select
            Select the Rank fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Rank filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.RankCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Rank.prisma().count()

        # results: prisma.types.RankCountAggregateOutput
        results = await Rank.prisma().count(
            select={
                '_all': True,
                'id': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.RankCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.RankWhereInput] = None,
        cursor: Optional[types.RankWhereUniqueInput] = None,
    ) -> types.RankCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.RankCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.RankWhereInput] = None,
        cursor: Optional[types.RankWhereUniqueInput] = None,
    ) -> Union[int, types.RankCountAggregateOutput]:
        """Count the number of Rank records present in the database

        Parameters
        ----------
        select
            Select the Rank fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Rank filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.RankCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Rank.prisma().count()

        # results: prisma.types.RankCountAggregateOutput
        results = await Rank.prisma().count(
            select={
                '_all': True,
                'name': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.RankCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.RankWhereInput] = None
    ) -> int:
        """Delete multiple Rank records.

        Parameters
        ----------
        where
            Optional Rank filter to find the records to be deleted

        Returns
        -------
        int
            The total number of Rank records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all Rank records
        total = await Rank.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.RankScalarFieldKeys'],
        *,
        where: Optional['types.RankWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.RankAvgAggregateInput'] = None,
        sum: Optional['types.RankSumAggregateInput'] = None,
        min: Optional['types.RankMinAggregateInput'] = None,
        max: Optional['types.RankMaxAggregateInput'] = None,
        having: Optional['types.RankScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.RankCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.RankScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.RankScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.RankGroupByOutput']:
        """Group Rank records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar Rank fields to group records by
        where
            Rank filter to select records
        take
            Limit the maximum number of Rank records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.RankGroupByOutput]
            A list of dictionaries representing the Rank record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group Rank records by min_rating values
        # and count how many records are in each group
        results = await Rank.prisma().group_by(
            ['min_rating'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models